# .kodiak.toml

version = 1

[merge]
require_automerge_label = true
automerge_label = ["automerge", "🚀 it!"]
blocking_labels = ["block", "🚫 it!"]
method = "squash"
delete_branch_on_merge = true

[merge.message]
title = "pull_request_title"

[update]
always = true
